### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by LaihoE** [Mvaaras/ot2022#1]
(Koodi ladattu 28.4 13:00)

Ohjelma toimii odotetusti ja latauksessa ei ongelmia. Oikein mukava pelata pari kierrosta.

## Testit
Tykkäsin erityisesti testeistä. testit ovat "atomiset" ja testien nimistä ymmärtää helposti mistä on kyse. Jos jotain parannettavaa on pakko keksiä niin sana "the" ei ole hirveän tärkeä funktion nimessä. (testifunktioissa ei ehkä niin väliä nimien suhteen)

## Koodi
Koodissa ei yhtään "isoa ongelmaa", alla olevat huomautukset enemmän suosituksia. 

### gamelogic.py

- Nätisti jaettu kolmeen luokkaan. Näppärät pienet funktiot.
- Koodi kaipaisi hieman kommentteja. esim. ```self.turn = 3-self.turn```  on kiva kikka, mutta kaipaisin kyllä sille kommentin. Samoin on vaikeata ulkopuolisena ymmärtää että self.points on lista jossa self.points[0] on pelaajan 1 pisteet ja self.points[1] on toisen pelaajan pisteet. Selkeää tämä oli sen jälkeen kun olin katsonut interface koodia, mutta ulkopuolisilla harvoin on aikaa lukea koko koodi. Toinen mahdollisuus olisi luoda sanakirja muotoa:  
```points = {player1: pisteet, player2: pisteet}```

### interface.py
- Taas nätisti jaettu luokkiin.  
- Interface luokan voisi kyllä jakaa pienempiin palasiin (kommentoit tätä itse, mutta jakaisin sen viellä useampaan palaan). If screen_mode on yli 50 riviä pitkä (jaettu kolmeen eri IF). Mahdollisesti voisit luoda oman funktion tai vastaavan jokaiselle screen modelle esim.
```python 
if screen_mode == 1:
    func1()
if screen_mode == 2:
    func2()
if screen_mode == 3:
    func3()
```
Muuten näyttää hyvältä.

## GUI
- Värit bugasivat hieman, välillä arvatessa oli värejä, joskus oikeat värit syttyivät joskus eivät (jos oli tarkoitus toimia näin niin en vain ymmärtänyt logiikkaa).
- "scoreboard" voisi olla keskellä alapalkkia.
-  Muuten GUI oikein sopiva.

**Comment by Mvaaras** [comment]
Kiitos tuhdista ja asianmukaisesta palautteesta! Arvostan suuresti parannusehdotuksia ja kehuja. 

Kysymystä "Väreistä" en välttämättä kuitenkaan ymmärtänyt oikein. Avatut kortit ovat kaikki png-kuvia, joista osan tausta on tällä hetkellä saman värinen kuin suljetun kortin, ja osan ei. Aiheuttiko tämä hämmennystä vai oliko pygamella jotakin muita ongelmia?

**Comment by LaihoE** [comment]
> 

Aivan, kuvat olivat vain eri värisiä. Jotenkin tuntui hieman erikoiselta pelatessa, mutta nytten jälkeenpäin ajateltuna ehkä se onkin ihan hyvä olla näin.
